### ISSUE TITLE
Want more "Related" rovers?

### ISSUE THREAD

**Issue by Roger-random** [sethfischer/osr#2]
What is the criteria for "Related projects": who's in, and who's out?

I'm honored my Sawppy was deemed worthy, and there are many more projects I've come across during my research. I wrote a series on them, each with my quick overview of their design. Please feel free to use this list as reference and add whichever designs fit your criteria for "Related projects" and ignore those who do not.

- Some rovers like the "littleBits Space Rover Inventor Kit" bear no resemblance to JPL explorers sent to Mars, they just have the word "rover" in their name. https://newscrewdriver.com/2020/12/07/window-shopping-littlebits-space-rover-inventor-kit/
- ServoCity's Bogie Runt Rover actually has a rocker-bogie suspension, but wheels do not steer. https://newscrewdriver.com/2020/12/08/window-shopping-servocity-bogie-runt-rover/
- 4tronix M.A.R.S. Rover has steerable wheels, but I saw room for improvement in the steering geometry. https://newscrewdriver.com/2020/12/09/window-shopping-4tronix-m-a-r-s-rover/
- Of course someone has built a rover out of LEGO, but it is not as functional as the others on this list while also being extremely expensive. https://newscrewdriver.com/2020/12/10/window-shopping-lego-rovers/
- Jakob Krantz has been working on a rover for several years. https://newscrewdriver.com/2020/12/11/quick-look-jakob-krantz-mars-rover/
- Frédéric Jelmoni’s rover is a little younger https://newscrewdriver.com/2020/12/12/quick-look-frederic-jelmonis-reproduction-du-rover-mars-2020/
- Bricolabs designs are simpler and more in line with my intent to make Sawppy easier to build. https://newscrewdriver.com/2020/12/13/quick-look-bricolabs-rovers/
- Ryan Kinnett's project is about the same age as Sawppy, but has gone dormant on account of parenthood https://newscrewdriver.com/2020/12/14/quick-look-ryan-kinnetts-micro-rover/
- European Space Agency has a little ExoMy to go with ESA's actual Mars rover. (Which is sadly no longer launching this year, on account of its original plan to launch on a Russian rocket and... well....)  Very cute, it faithfully copies ExoMars _Rosalind Franklin_ rover's triple-bogie suspension geometry instead of rocker-bogie used by JPL Mars rovers. https://newscrewdriver.com/2020/12/15/quick-look-esa-exomy-rover/

---

Since the time I wrote the above, I have come across this one which I have yet to examine in more detail.

RB-0 which I learned from 
(https://twitter.com/NVIDIAEmbedded/status/1393211876717342720) which linked to (https://developer.nvidia.com/embedded/community/jetson-projects?linkId=100000044774919#rb_0) which linked to (https://www.hackster.io/planktonrobo/rb-0-jetson-nano-powered-rover-ca242a)

---

Plush rovers probably do not fit your criteria.
- https://twitter.com/DoktorPiornik/status/1297943047683158018?cxt=HHwWhMC9_eaUnIMkAAAA
- https://twitter.com/sofiessketches/status/1445503126463651846

**Comment by sethfischer** [comment]
Thank you @Roger-random! This is certainly a useful and interesting list. 

I had indented that the _Related projects_ section would be rovers from which I drew inspiration for my (in progress) design.

But I think this list will be on interest to many so I'll leave this issue open with the intention of incorporating it somehow.

**Comment by sethfischer** [comment]
Closed by 93e82b72846795818d47188297aa12a4082de126. Thanks @Roger-random I've given you credit in the commit message.
